name: Redis Stack Build

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron:  '30 5 * * 1'
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ${{ secrets.REGISTRY }}
  USERNAME: ${{ secrets.USERNAME }}
  NAMESPACE: ${{ secrets.NAMESPACE }}
  # github.repository as <account>/<repo>
  IMAGE_NAME: redis-stack


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.12.0
        with:
          context: .
          file: ./Dockerfile.redis
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push Docker RedisStackServer image
        id: build-and-push-redis-stack-server
        uses: docker/build-push-action@v6.12.0
        with:
            context: .
            file: ./Dockerfile.redis-stack-server
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/redis-stack-server:latest
            labels: ${{ steps.meta.outputs.labels }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
      - name: Build and push Docker Redis latest image
        id: build-and-push-redis-latest
        uses: docker/build-push-action@v6.12.0
        with:
            context: .
            file: ./Dockerfile.redis
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/redis:latest
            labels: ${{ steps.meta.outputs.labels }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
